### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by anderssone** [xombiemp/rutorrentMobile#5]
Hello,

Thanks for a great plugin.
Just wanted to check if it's possible to turn off the language detection?

Brgds,
Erik

**Comment by xombiemp** [comment]
What are you trying to do?

**Comment by anderssone** [comment]
I want rutorrentMobile to be in English only and not detect the language settings of my mobile device if that is possible.

**Comment by xombiemp** [comment]
The language is based on the preference set in rutorrent.  It does not detect the language of your device.  Besides, all the language files are in English anyways, because there has been no translation done.  There are only 3 strings added with this plugin and they will always show as English until I receive some translations.

**Comment by anderssone** [comment]
Ok, my language setting in rutorrent is English and the language on my phone is Swedish and rutorrent is shown in Swedish so somehow it's being translated.
